apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: prod
spec:
  releaseName: hello-arc-prod
  chart:
    path: charts/hello-arc
    ref: master
    #git: https://github.com/rramankutty0/hello_arc_priv.git
    #secretRef: 26d11aab449bded4750570786186ba8af8f2cd74
    git: https://github.com/rramankutty0/hello_arc.git
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 4
    env:
      name: MESSAGE
      value: Azure Arc enabled K8s GitOps Demo!
